apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: fastapi-react-project
  namespace: argocd
  labels:
    app: fastapi-react-app
spec:
  description: "Projeto para aplicação FastAPI + React"
  
  # Repositórios permitidos
  sourceRepos:
  - 'https://github.com/periclesandrade21/jenkins_nodejs.git'
  - 'https://helm.elastic.co'
  - 'https://prometheus-community.github.io/helm-charts'
  
  # Destinos permitidos
  destinations:
  - namespace: app-dev
    server: https://kubernetes.default.svc
  - namespace: app-hml
    server: https://kubernetes.default.svc
  - namespace: monitoring
    server: https://kubernetes.default.svc
  - namespace: logging
    server: https://kubernetes.default.svc
  
  # Recursos permitidos no cluster
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  - group: networking.k8s.io
    kind: NetworkPolicy
  
  # Recursos permitidos nos namespaces
  namespaceResourceWhitelist:
  - group: ''
    kind: Service
  - group: ''
    kind: Secret
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: PersistentVolumeClaim
  - group: apps
    kind: Deployment
  - group: apps
    kind: ReplicaSet
  - group: apps
    kind: StatefulSet
  - group: networking.k8s.io
    kind: Ingress
  - group: autoscaling
    kind: HorizontalPodAutoscaler
  - group: batch
    kind: Job
  - group: batch
    kind: CronJob
  
  # Roles permitidos
  roles:
  - name: admin
    description: "Administrador do projeto"
    policies:
    - p, proj:fastapi-react-project:admin, applications, *, fastapi-react-project/*, allow
    - p, proj:fastapi-react-project:admin, repositories, *, *, allow
    groups:
    - argocd-admins
  
  - name: developer
    description: "Desenvolvedor com acesso limitado"
    policies:
    - p, proj:fastapi-react-project:developer, applications, get, fastapi-react-project/*, allow
    - p, proj:fastapi-react-project:developer, applications, sync, fastapi-react-project/*, allow
    groups:
    - developers
  
  # Configurações de sync
  syncWindows:
  - kind: allow
    schedule: '* * * * *'
    duration: 24h
    applications:
    - '*-dev'
    manualSync: true
  - kind: deny
    schedule: '0 18 * * 1-5'
    duration: 12h
    applications:
    - '*-hml'
    manualSync: false
    timeZone: America/Sao_Paulo