apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-hml

resources:
- ../base/namespace.yaml
- ../base/backend-deployment.yaml
- ../base/frontend-deployment.yaml
- ../base/mongodb-deployment.yaml
- ../base/configmap.yaml
- secrets.yaml
- ingress.yaml
- hpa.yaml
- network-policy.yaml

patchesStrategicMerge:
- deployment-patches.yaml

configMapGenerator:
- name: app-config-hml
  literals:
  - environment=homologation
  - log_level=INFO
  - backend_replicas=2
  - frontend_replicas=2

images:
- name: your-registry.com/fastapi-backend
  newTag: latest
- name: your-registry.com/react-frontend
  newTag: latest

commonLabels:
  environment: homologation
  version: v1